@authHost = http://localhost:5041
@figuresHost = http://localhost:5124

### 1. Registrar tutor (solo la primera vez)
POST {{authHost}}/auth/register
Content-Type: application/json

{
  "name": "Carlos Ramirez",
  "email": "android@example.com",
  "password": "TutorPass123!",
  "role": "tutor",
  "country": "CO",
  "grade": "Padre o Madre",
  "neurodivergency": "None",
  "age": 30,
  "genre": "M"
}

###

### 2. Registrar estudiante (solo la primera vez)
POST {{authHost}}/auth/register
Content-Type: application/json

{
  "name": "Ana Lopez",
  "email": "gabo@example.com",
  "password": "StudentPass123@",
  "role": "student",
  "country": "CO",
  "neurodivergency": "None",
  "age": 10,
  "genre": "F"
}

###

### 3. Login tutor
POST {{authHost}}/auth/login
Content-Type: application/json

{
  "email": "android@example.com",
  "password": "TutorPass123!"
}

###

### 4. Login estudiante
POST {{authHost}}/auth/login
Content-Type: application/json

{
  "email": "ana.student@example.com",
  "password": "StudentPass123"
}

###

### 5. Asignar tutor al estudiante (requiere token de tutor)
@tutorToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiZW1haWwiOiJzZXRoQGV4YW1wbGUuY29tIiwicm9sZSI6InR1dG9yIiwiaXNzIjoiZmlndXJhc3FlLWF1dGgiLCJhdWQiOiJmaWd1cmFzcWUtY2xpZW50IiwiaWF0IjoxNzc3MDA1MDc4LCJleHAiOjE3NzcwMDg2Nzh9.h_-2nNFJhHZPmfwXvUFMNG4oFM-iqpf73PHJb8IFHjQ
POST {{figuresHost}}/tutors/assign-student
Authorization: Bearer {{tutorToken}}
Content-Type: application/json

{
  "studentEmail": "songohan@capsule.cc",
  "tutorEmail": "songoku@capsule.cc"
}

