@host = http://localhost:5124
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzMyIsImVtYWlsIjoiZ2Fib0BleGFtcGxlLmNvbSIsInJvbGUiOiJzdHVkZW50IiwiaXNzIjoiZmlndXJhc3FlLWF1dGgiLCJhdWQiOiJmaWd1cmFzcWUtY2xpZW50IiwiaWF0IjoxNzc4NTMyMjEzLCJleHAiOjE3Nzg1MzU4MTN9.o2RIff3FUgEOIcE6Q_pA8L7kvlmJVtqjVB9Fmh6aUwg
@studentId = 33
@tutorId = 13

### Obtener estudiantes (depende del rol del token)
GET {{host}}/students
Authorization: Bearer {{token}}
Accept: application/json

### Obtener estudiante por id
  "name": "Ana Lopez Actualizada",
GET {{host}}/students/{{studentId}}
Authorization: Bearer {{token}}
Accept: application/json

### Crear estudiante
POST {{host}}/students
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idTutor": {{tutorId}},
  "name": "Ana Lopez",
  "email": "ana.student@example.com",
  "passwordHash": "StudentPass123",
  "age": 10,
  "gender": "F",
  "country": "CO",
  "neurodivergency": "None"
}

### Actualizar estudiante
PUT {{host}}/students/{{studentId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "idTutor": {{tutorId}},
  "name": "Ana Lopez Actualizada",
  "email": "ana.student@example.com",
  "passwordHash": "StudentPass1234",
  "age": 11,
  "gender": "M",
  "country": "CO",
  "neurodivergency": "None"
}

### Obtener ids de estudiantes por tutor
GET {{host}}/students/tutor/{{tutorId}}/ids
Authorization: Bearer {{token}}
Accept: application/json

### Obtener ids de sesiones por estudiante
GET {{host}}/students/{{studentId}}/sessions/ids
Authorization: Bearer {{token}}
Accept: application/json

### Eliminar estudiante
DELETE {{host}}/students/{{studentId}}
Authorization: Bearer {{token}}
Accept: application/json
