@host = http://localhost:5124
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4IiwiZW1haWwiOiJzZXRob0BleGFtcGxlLmNvbSIsInJvbGUiOiJ0dXRvciIsImlzcyI6ImZpZ3VyYXNxZS1hdXRoIiwiYXVkIjoiZmlndXJhc3FlLWNsaWVudCIsImlhdCI6MTc3NzAwNzY3MywiZXhwIjoxNzc3MDExMjczfQ.cMjhyFEiONto8YX4PaKS0njynMzKgO8ghJhDUPYQlCY
@tutorId = 8

### Obtener todos los tutores
GET {{host}}/tutors
Authorization: Bearer {{token}}
Accept: application/json

### Obtener tutor por id
GET {{host}}/tutors/{{tutorId}}
Authorization: Bearer {{token}}
Accept: application/json

### Obtener estudiantes asignados a un tutor
GET {{host}}/tutors/{{tutorId}}/students
Authorization: Bearer {{token}}
Accept: application/json

### Crear tutor
POST {{host}}/tutors
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Carlos Ramirez",
  "email": "carlos.gabriel@example.com",
  "passwordHash": "TutorPass123",
  "country": "CO",
  "gender": "Masculino",
  "age": 35,
  "grade": "Maestria"
}

### Actualizar tutor
PUT {{host}}/tutors/{{tutorId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Carlos Ramirez Actualizado",
  "email": "carlos.tutorrrrrrrrr@example.com",
  "country": "CO",
  "gender": "Masculino",
  "age": 36,
  "grade": "Doctorado"
}

### Asignar tutor a estudiante por email
POST {{host}}/tutors/assign-student
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "studentEmail": "ana.student@example.com",
  "tutorEmail": "setho@example.com"
}

### Eliminar tutor
DELETE {{host}}/tutors/{{tutorId}}
Authorization: Bearer {{token}}
Accept: application/json
